My_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from My_chat import settings


urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('chat.urls')),
]

if settings.DEBUG:
      urlpatterns += static(settings.MEDIA_URL, document_root=
                            settings.MEDIA_ROOT)
      urlpatterns += static(settings.STATIC_URL, document_root=
      settings.STATIC_ROOT)

chat/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns = [
        path('', views.home, name='home'),
        path('account/create/', views.createUserView, name='signup'),
        path('account/login/', views.loginView, name='login'),
        path('account/signout/', views.signoutView, name='signout'),
        path('account/create_message/', views.createMessageView, name='create_message'),
        path('account/mychat/', views.createMessageView, name='mychat'),
]

chat/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.shortcuts import render
from django.views import View


class Chat(models.Model):
    """Модель комнаты чата"""
    creater = models.ForeignKey(User, verbose_name="Создатель", on_delete=models.CASCADE)
    invited = models.ManyToManyField(User, verbose_name="Участники", related_name="invited_user")
    date = models.DateTimeField("Дата создания", auto_now_add=True)


    class Meta:
        verbose_name = "Чат"
        verbose_name_plural = "Чаты"


class Message(models.Model):
    """Модель чата"""
    chat = models.ForeignKey(Chat, verbose_name="Чат", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    text = models.TextField("Сообщение", max_length=500)
    date = models.DateTimeField("Дата отправки", auto_now_add=True)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=250)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'password1', 'password2', 'email')

chat/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group, User
from django.views import View

from .forms import CreateUserForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .models import Chat, Message


def home(request):
    return render(request,'home.html')

def createUserView(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            signup_user = User.objects.get(username=username)

    else:
        form = CreateUserForm()
    return render(request, 'create_user.html', {'form': form})


def loginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                return redirect('create_user')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def signoutView(request):
    logout(request)
    return redirect('home')


def createMessageView(request):

    if request.method == 'POST':
        return render(request, 'create_message.html')

    if request.method == 'GET':
        return render(request, 'create_message.html')

chat/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

    <style type="text/css">
        .material-icons.md-48 { font-size: 48px; }
    </style>

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-dark">
        <a href="{% url 'home' %}" class="navbar-brand"><i class="material-icons text-warning md-48">chat</i></a>

        {% if request.user.is_authenticated and request.user.first_name%}
            <button class="navbar-toggler bg-warning" data-bs-toggle="collapse" data-bs-target="#navbar"><span class="navbar-toggler-icon" ></span></button>
            <div id="navbar" class="collapse navbar-collapse justify-content-between">
            <ul class="navbar-nav">
                <li class="nav-item dropdown"><a class="nav-link text-light text-uppercase font-weight-bold px-3 dropdown-toggle" data-bs-toggle="dropdown" href="">Сообщения</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'create_message' %}">Создать сообщение</a>

                        <a class="dropdown-item" href="">Мои сообщения</a>
                    </div>
                </li>
                <li class="nav-item"><span class="nav-link text-light text-uppercase font-weight-bold px-3" href="">{{request.user.first_name }}</span></li>
                <li class="nav-item"><a class="nav-link text-light text-uppercase font-weight-bold px-3" href="{% url 'signout' %}">Выход</a></li>
            </ul>
            <form class="form-inline">
                <div class="input-group">
                    <label>
                        <input type="text" placeholder="Search" >
                    </label>
                    <div>
                        <button class="btn-warning"><i class="material-icons md-36" >person_search</i></button>
                    </div>
                </div>
            </form>
            </div>

        {% else %}
        <button class="navbar-toggler bg-warning" data-bs-toggle="collapse" data-bs-target="#navbar"><span class="navbar-toggler-icon" ></span></button>
            <div id="navbar" class="collapse navbar-collapse justify-content-between">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link text-light text-uppercase font-weight-bold px-3" href="{% url 'signup' %}">Регистрация</a></li>
                <li class="nav-item"><a class="nav-link text-light text-uppercase font-weight-bold px-3" href="{% url 'login' %}">Войти</a></li>
            </ul>
            </div>

        {% endif %}
    </nav>

{% block content %}
{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

 {% include 'footer.html' %}

chat/templates/create_message.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Create New Account
{% endblock %}

{% block content %}

    <div>
        {% if not user.is_valid %}
            <div>
                <br>
                <h1 class="product_title text-center">
                    Создать сообщение
                </h1>
                <br>
                <div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light">
                    <br>
                    <p>Пожалуйста, напишите сообщение, и выберете кому вы хотите отправить его</p>
                    <form method="get" action="{% url 'home' %}">
                        <p>{{ crispy }}</p>
                        <p>
                        <input v-model="user" type="text" placeholder="Имя пользователя"/>
                        <p>
                        <textarea cols="50" rows="10" name="text" type="text" placeholder="Текст сообщения"></textarea>
                        <p>
                        <button type="text" name="button" class="btn btn-secondary">Отправить</button>
{#                        <button type="submit" name="button" class="btn btn-secondary">Отправить</button>#}
                    </form>
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

chat/templates/create_user.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    Create New Account
{% endblock %}

{% block content %}

    <div>
        {% if not form.is_valid %}
            <div>
                <br>
                <h1 class="product_title text-center">
                    Регистрация
                </h1>
                <br>
                <div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light">
                    <br>
                    <p>Пожалуйста введите следующую информацию для создания нового аккаунта</p>
                    <form method="post">
                        {% csrf_token %}
                        <p>{{ form | crispy }}</p>
                        <button type="submit" name="button" class="btn btn-secondary">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        {% else %}
        <div class="mx-auto">
            <br>
            <h1 class="product_tittle text-center">
                Ваш аккаунт был успешно создан
            </h1>
            <br>
            <div>
                <a href="{% url 'login' %}">Войти в чат с помощью логина и пароля </a>
            </div>
        </div>
        {% endif %}
    </div>

{% endblock %}

chat/templates/dialogs.html
{% load i18n %}
<div class="panel">
        {% load tz %}
        {% if chats.count == 0 %}
            <div class="panel panel-body">{% trans "Нет ни одного начатого диалога" %}</div>
        {% endif %}
        {% for chat in chats %}
            {% if chat.message_set.count != 0 %}
                {% with last_message=chat.message_set.last %}
{#                    {% {{request.user.first_name }} user chat as companion %}#}
                        <img class="avatar-messages" src="{{ companion.userprofile.get_avatar }}">
                        <div class="reply-body">
                            <ul class="list-inline">
                                <li class="drop-left-padding">
                                    <strong class="list-group-item-heading">{{ companion.username }}</strong>
                                </li>
                                <li class="pull-right text-muted"><small>{{ last_message.pub_date|utc }}</small></li>
                            </ul>
                            {% if companion != last_message.author %}
                                <div>
                                    <img class="avatar-rounded-sm" src="{{ last_message.author.userprofile.get_avatar }}">
                                    <div class="attached-reply-body {% if not last_message.is_readed %}unreaded{% endif %}">{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                                </div>
                            {% else %}
                                <div>{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                            {% endif %}
                        </div>
                    </a>
                {% endwith %}
            {% endif %}
        {% endfor %}
    </div>

chat/templates/footer.html
<footer class ="bg-dark text-white mt-6 p-5">
    <div class="container">
        <p class="lead text-center">Designed by Lepin German &copy; 2021 Moscow</p>
    </div>
</footer>

chat/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="background">
        <div class="row-cols-1">
            <img src="{% static 'images/city.jpg' %}">
        </div>
    </div>
{% endblock %}

chat/templates/login.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% load static %}

{% block title %}
    Log in
{% endblock %}

{% block content %}

    <div class="container">
        <br>
        <h1 class="product_title text-center" >
            Вход
        </h1>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 mx-auto bg-light">
            <div>
                <br>
                <h2 class="product_title"</h2>
                <form method="post">
                    {% csrf_token %}
                    <p>{{ form | crispy }}</p>
                    <button type="submit" class="btn btn-secondary">Войти</button>
                </form>
                <br>
            </div>
            <div class="row">
                <div class ="col-12 col-sm-12 col-lg-6 custom_div">
                    <a href="{% url 'signup' %}" class="btn btn-secondary">Зарегистрироваться</a>
                </div>
            </div>
        </div>
        <br>
    </div>
    <br>
{% endblock %}

chat/templates/mychats.html
{% extends 'base.html' %}
{% load i18n %}

{% load crispy_forms_tags %}

{% block title %}
    Create New Account
{% endblock %}

{% block content %}

{% if not chat %}
    <div class="panel panel-body">
        {% trans "Невозможно начать беседу. Не найден пользователь или вы не имеете доступа к данной беседе." %}
    </div>
{% else %}
    {% load tz %}
    {% if chat %}
        <div id="messages" class="panel">
            <div id="innerMessages">
                {% for message in chat.message_set.all %}
                        {% include 'message.html' with message_item=message %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <div id="message_form">
        <form id="message-form" class="panel panel-body" method="post" >
            {% load bootstrap3 %}
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-default btn-sm" onclick="return ETextEditor.validateForm('message-form')"><span class="ico ico-comment"></span>{% trans "Отправить" %}</button>
        </form>
    </div>
{% endif %}

{% endblock %}